apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-term-api-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
    app: legal-term-api
 template:
  metadata:
    labels:
     app: legal-term-api
  spec:
    containers:
    - name: legal-term-api
      image: tatia7/legal-term-api:1f12a885f5359ba003b917bc50130886934b249e
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8000 
