apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-term-api-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
    app: legal-term-api
 template:
  metadata:
    labels:
     app: legal-term-api
  spec:
    containers:
    - name: legal-term-api
      image: tatia7/legal-term-api:21f64e7321ad8f91eb0e3e28a964ada310fa5470
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8000 
